# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  open: true
  culture: FR # will be the default country in location prompt
  idle_time: 60000 #allowed idle time in milliseconds before reset (default: 90000, set to false to disable)
  payment_method_id: 3
  location_prompt: true #display a popup asking for customer geo origin on checkout
  admin: true
  user:
    templating: kiosk
    #other_templates: []
    must_authenticate: false
    #session_ns: ''
  io:
    devices: 
      ept:
        type: 'serial'
        params:
          baudrate: 1200
          comName: '/dev/ttyACM0'
          databits: 7,
          parity: 'even'
          pnpId: 'usb-079b_0028-if00'
      ticketPrinter:
        type: 'usb'
        params:
          pid: 1,
          vid: '1305'
      invoicePrinter:
        type: 'usb'
        params:
          pid: '14864'
          vid: '7306'
  ui:
    logo: '/private/logo.png'
    labels: 
      price: 'name'
    texts: # this config will override texts stored in database
      menu_manifestations: 
        fr: 'Activités'
        en : 'Museum activities'
      menu_museum: 
        fr: 'Visites'
        en: 'Museum visits'
      menu_store: 
        fr: 'Boutique'
        en: 'Store'
      breadcrumb_home:
        fr: 'Accueil'
        en: 'Home'
      breadcrumb_products:
        fr: 'Liste des produits'
        en: 'Products'
      cart_total:
        fr: 'Total'
        en: 'Total'
      cart_validate:
        fr: 'Valider'
        en: 'Checkout'
      location_title:
        en: 'Please enter your post code or country'
        fr: 'Veuillez entrer votre code postal ou votre pays'
      location_close: 
        en: 'Continue to payment'
        fr: 'Continuer'
      postcode:
        en: 'Post code'
        fr: 'Code postal'
      postcode_validation:
        en: 'Post code must onlay contain numbers'
        fr: 'Le code postal doit être composé uniquement de chiffres'
      retry: 
        en: 'Retry'
        fr: 'Réessayer'
      cancel:
        en: 'Cancel'
        fr: 'Annuler'
      hardware_title:
        en: 'Out of order'
        fr: 'Hors service'
      hardware_details:
        en: 'Please head to the front office for help'
        fr: 'Veuillez vous diriger vers le poste d'accueil
      payment_title:
        en: 'Please follow payment terminal instructions'
        fr: 'Veuillez suivre les instructions sur le terminal de paiement'
      payment_failure:
        en: 'Payment failed'
        fr: 'Le paiement a échoué'
      payment_success_title:
        en: 'Payment successfull'
        fr: 'Paiement accepté'
      payment_success_details:
        en: 'Please wait while your tickets are being printed'
        fr: 'Veuillez patienter pendant l'impression de vos billets'
      ticket_failure:
        en: 'Ticket printing failed'
        fr: 'Erreur d'impression'
      final_title:
        en: 'Thank you for your order'
        fr: 'Merci pour votre commande'
      final_details:
        en: 'Please wait for your receipt'
        fr: 'Veuillez attendre l'impression de votre reçu'